import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Script from 'next/script';

const kumbh_sans = Kumbh_Sans({ subsets: ["latin"], variable: "--font-kumbh" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"
        ></Script>
      </head>

      <body className={kumbh_sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
